section: screens
	mac-main:
		alt = alt
		meta = meta
		shift = shift
		super = super
		ctrl = ctrl
		halfDuplexNumLock = false
		xtestIsXineramaUnaware = false
		halfDuplexCapsLock = false
		halfDuplexScrollLock = false
		switchCorners = none 
		altgr = alt
	linuxclient:
		alt = super
		meta = meta
		shift = shift
		super = alt
		ctrl = ctrl
		halfDuplexNumLock = false
		xtestIsXineramaUnaware = false
		halfDuplexCapsLock = false
		halfDuplexScrollLock = false
		switchCorners = none 
		altgr = alt
end

section: aliases
end

section: links
	mac-main:
		right(0,100) = linuxclient(0,100)
	linuxclient:
		left(0,100) = mac-main(0,100)
end

section: options
	heartbeat = 5000
	relativeMouseMoves = true
	clipboardSharing = true
	clipboardSharingSize = 4000
	win32KeepForeground = true
	disableLockToScreen = false
	keystroke(Control+Alt+q) = switchInDirection(left)
	keystroke(Control+Alt+w) = switchInDirection(right)
end
