#!/usr/bin/env bash
# verify.sh - QA probes for the dotfiles repo + an installed target home.
#
#   bash scripts/verify.sh              # checks the repo + conformance vs live ~
#   bash scripts/verify.sh --prefix /tmp/fake   # checks an installed sandbox
#   bash scripts/verify.sh --repo-only  # skip live conformance diffs
set -uo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_HOME="${HOME}"
REPO_ONLY=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) TARGET_HOME="$2"; shift 2 ;;
    --repo-only) REPO_ONLY=1; shift ;;
    *) echo "unknown: $1" >&2; exit 2 ;;
  esac
done

PASS=0; FAIL=0
ok()   { printf '  PASS  %s\n' "$*"; PASS=$((PASS+1)); }
bad()  { printf '  FAIL  %s\n' "$*"; FAIL=$((FAIL+1)); }
need(){ command -v "$1" >/dev/null 2>&1; }

echo "==> Verifying repo + target home: $TARGET_HOME"

# 1. repo integrity: required files exist & non-empty
echo "-- repo file presence --"
for f in home/.zshrc home/.zprofile home/.tmux.conf home/.tmux-status.conf \
         nvim/init.lua nvim/lazy-lock.json \
         tmux/resurrect-save-strategy/hermes_agents.sh \
         tmux/resurrect-helpers/hermes_history_after_restore.sh \
         tmux/scripts/save_terminal_geometry.sh \
         tmux/LaunchAgents/Tmux.Start.plist \
         apps/claude/settings.json apps/claude/keybindings.json \
         apps/brew-formulas.txt apps/brew-casks.txt \
         terminal/Basic.terminal scripts/install.sh scripts/verify.sh \
         README.md; do
  if [[ -s "$REPO_DIR/$f" ]]; then ok "$f present"; else bad "$f MISSING/empty"; fi
done

# 2. shell syntax
echo "-- shell syntax --"
for s in home/.zshrc; do
  if zsh -n "$REPO_DIR/$s" 2>/dev/null; then ok "zsh -n $s"; else bad "zsh -n $s"; fi
done
for s in scripts/install.sh scripts/verify.sh scripts/install-fzf-release.sh \
         tmux/resurrect-save-strategy/hermes_agents.sh \
         tmux/resurrect-helpers/hermes_history_after_restore.sh \
         tmux/scripts/save_terminal_geometry.sh; do
  if bash -n "$REPO_DIR/$s" 2>/dev/null; then ok "bash -n $s"; else bad "bash -n $s"; fi
done

# 3. JSON validity (claude + nvim lock)
echo "-- JSON validity --"
for j in apps/claude/settings.json apps/claude/keybindings.json nvim/lazy-lock.json; do
  if python3 -c "import json,sys; json.load(open('$REPO_DIR/$j'))" 2>/dev/null; then ok "json $j"; else bad "json $j"; fi
done

# 4. Terminal profile parses + carries Option-as-Meta
echo "-- terminal profile --"
if python3 -c "import plistlib;d=plistlib.load(open('$REPO_DIR/terminal/Basic.terminal','rb'));b=d['Window Settings']['Basic'];assert b['useOptionAsMetaKey'] is True" 2>/dev/null; then
  ok "Basic.terminal parses + Option-as-Meta=ON"
else
  bad "Basic.terminal invalid or Option-as-Meta off"
fi

# 5. no leftover @HOME@ placeholders in installed files, and scripts in target
echo "-- sandbox/live install checks --"
if grep -rl '@HOME@' "$TARGET_HOME/.local/bin" 2>/dev/null | grep -q .; then
  bad "@HOME@ leftover in installed launchers"
else
  ok "no @HOME@ leftover in ~/.local/bin"
fi
for l in hermes fonttoggle; do
  if [[ -x "$TARGET_HOME/.local/bin/$l" ]]; then ok "launcher $l installed+exec"; else bad "launcher $l missing"; fi
done
# Launchers this repo installs (scan only these, so real-machine binaries like
# fzf/claude/cua-driver in ~/.local/bin are not mis-flagged as bad launchers).
REPO_LAUNCHERS="hermes hermes-acp fonttoggle hermes-update-safe"
for l in $REPO_LAUNCHERS; do
  [[ -f "$TARGET_HOME/.local/bin/$l" ]] || { bad "launcher $l missing"; continue; }
  if bash -n "$TARGET_HOME/.local/bin/$l" 2>/dev/null; then :; else bad "bash -n of launcher $l"; fi
done
ok "launcher shell-syntax scan complete"

# 6. live tmux conformance (only when server/config present)
echo "-- tmux live checks --"
if [[ "$REPO_ONLY" -eq 0 && -f "$TARGET_HOME/.tmux.conf" ]]; then
  if diff -q "$REPO_DIR/home/.tmux.conf" "$TARGET_HOME/.tmux.conf" >/dev/null 2>&1; then
    ok "repo .tmux.conf == installed .tmux.conf"
  else
    bad ".tmux.conf differs (repo vs installed)"
  fi
  if [[ -f "$TARGET_HOME/.tmux-status.conf" ]] && diff -q "$REPO_DIR/home/.tmux-status.conf" "$TARGET_HOME/.tmux-status.conf" >/dev/null 2>&1; then
    ok "repo .tmux-status.conf == installed"
  else
    bad ".tmux-status.conf differs/missing (note: regenerated by tmuxline.vim)"
  fi
fi
if tmux show -g prefix >/dev/null 2>&1; then
  p=$(tmux show -g prefix 2>/dev/null | awk '{print $2}')
  [[ "$p" == "C-a" ]] && ok "live prefix C-a" || bad "live prefix is $p (want C-a)"
  tmux show -g @resurrect-save-command-strategy 2>/dev/null | grep -q hermes_agents \
    && ok "resurrect strategy hermes_agents" || bad "resurrect strategy not set"
fi

# 7. nvim headless (when nvim + config present)
echo "-- nvim checks --"
if need nvim; then
  if [[ -f "$TARGET_HOME/.config/nvim/init.lua" ]] && diff -q "$REPO_DIR/nvim/init.lua" "$TARGET_HOME/.config/nvim/init.lua" >/dev/null 2>&1; then
    ok "nvim init.lua matches installed"
  else
    bad "nvim init.lua differs/missing"
  fi
  out=$(nvim --headless -c "lua print('nvim-ok')" -c 'qa!' 2>&1)
  grep -q "nvim-ok" <<<"$out" && ok "nvim headless starts clean" || bad "nvim headless issue: $out"
fi

# 8. conformance vs live canonical source (repo should match the real Mac)
if [[ "$REPO_ONLY" -eq 0 && "$TARGET_HOME" == "$HOME" ]]; then
  echo "-- live conformance (repo == canonical machine) --"
  for pair in \
      "home/.zshrc:.zshrc" "home/.zprofile:.zprofile" \
      "home/.tmux.conf:.tmux.conf" "home/.tmux-status.conf:.tmux-status.conf" \
      "nvim/init.lua:.config/nvim/init.lua" "nvim/lazy-lock.json:.config/nvim/lazy-lock.json" \
      "apps/claude/settings.json:.claude/settings.json" "apps/claude/keybindings.json:.claude/keybindings.json"; do
    repo="${pair%%:*}"; live="${pair##*:}"
    if [[ -f "$HOME/$live" ]] && diff -q "$REPO_DIR/$repo" "$HOME/$live" >/dev/null 2>&1; then
      ok "conform $repo == ~/$live"
    else
      bad "CONFORM $repo vs ~/$live (see diff)"
    fi
  done
fi

echo
echo "==> RESULT: $PASS pass, $FAIL fail"
[[ "$FAIL" -eq 0 ]] || { echo "   ^ review failures above."; exit 1; }
echo "   All checks passed."
